production:
  daily_requests_reminder_job:
    class: NotifyRequestsJob
    queue: requests_notifications
    schedule: every friday at 9am
    timezone: America/Guayaquil

development:
  daily_requests_reminder_job:
    class: NotifyRequestsJob
    queue: requests_notifications
    schedule: every friday at 9am
    timezone: America/Guayaquil